version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fsfe2
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # links:
    #  - fsfe2:fsfe2
    command: "/bin/sh -c 'while :; do sleep 15d & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  fsfe2:
    build: ./fsfe2
    environment:
      - PORT=3001
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 30d & wait $${!}; done;'"
